In [1]:
import pandas as pd

df = pd.read_csv("codes.csv")
df

,A00,0,A000,"Cholera due to Vibrio cholerae 01, biovar cholerae","Cholera due to Vibrio cholerae 01, biovar cholerae.1",Cholera
0,A00,1,A001,"Cholera due to Vibrio cholerae 01, biovar eltor","Cholera due to Vibrio cholerae 01, biovar eltor",Cholera
1,A00,9,A009,"Cholera, unspecified","Cholera, unspecified",Cholera
2,A010,0,A0100,"Typhoid fever, unspecified","Typhoid fever, unspecified",Typhoid fever
3,A010,1,A0101,Typhoid meningitis,Typhoid meningitis,Typhoid fever
4,A010,2,A0102,Typhoid fever with heart involvement,Typhoid fever with heart involvement,Typhoid fever
...,...,...,...,...,...,...
71698,Z991,2,Z9912,Encounter for respirator dependence during pow...,Encounter for respirator [ventilator] dependen...,Dependence on respirator
71699,Z992,NaN,Z992,Dependence on renal dialysis,Dependence on renal dialysis,Dependence on renal dialysis
71700,Z993,NaN,Z993,Dependence on wheelchair,Dependence on wheelchair,Dependence on wheelchair
71701,Z998,1,Z9981,Dependence on supplemental oxygen,Dependence on supplemental oxygen,Dependence on other enabling machines and devices
71702,Z998,9,Z9989,Dependence on other enabling machines and devices,Dependence on other enabling machines and devices,Dependence on other enabling machines and devices

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(df)

true_k = 5
model = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1)
model.fit(X)

print("Top terms per cluster:")
order_centroids = model.cluster_centers_.argsort()[:, ::-1]
terms = vectorizer.get_feature_names()
for i in range(true_k):
    print("Cluster %d:" % i),
    for ind in order_centroids[i, :10]:
        print(' %s' % terms[ind]),
    print

Top terms per cluster:
Cluster 0:
 cholerae
 vibrio
 biovar
 01
 cholera
 a000
 a00
Cluster 1:
 vibrio
 cholerae
 cholera
 biovar
 a000
 a00
 01
Cluster 2:
 cholera
 vibrio
 cholerae
 biovar
 a000
 a00
 01
Cluster 3:
 a00
 vibrio
 cholerae
 cholera
 biovar
 a000
 01
Cluster 4:
 a000
 vibrio
 cholerae
 cholera
 biovar
 a00
 01

/Users/mekari/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [3]:
print(model)

KMeans(max_iter=100, n_clusters=5, n_init=1)

In [6]:
from sklearn.metrics import silhouette_score
score = silhouette_score(X, model.labels_, metric='euclidean')
print('Silhouetter Score: %.3f' % score)

Silhouetter Score: 0.333